# Generated by Django 4.1.7 on 2023-05-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_flight_id_flight_flightid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='FlightDetails',
        ),
    ]
