# Generated by Django 4.1.7 on 2023-05-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_flight_flightdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seatTaken',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
