# Generated by Django 4.1.7 on 2023-05-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_seat_seattaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seatTaken',
            field=models.BooleanField(default=False),
        ),
    ]
